[tool.robotpy]
robotpy_version = "2025.3.2.0"
robotpy_extras = [
  "commands2",
  "navx",
  "pathplannerlib",
  "rev",
  "sim",
  "cscore",
  "pynetworktables"
]
requires = [
  "photonlibpy",
  "numpy",
  "pynetworktables"
]
